lg -r p -m "This one passed" -e "Test explanation"
lg -r p -m "This one also passed"
lg -r f -m "This one failed" -e "This was wrong because X"
lg -r p -m "This one passed too"
lg -r f -m "This one also failed" -e "This was wrong because Y"
