name: test
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: jfaz1/testing:latest
      volumes:
        - ${{ github.workspace }}:/work
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd /work/test && chmod +x ./test.sh && ./test.sh
          sleep 0.1 && lg -o && sleep 0.1
      - name: Save results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ github.workspace }}/test/results.csv
      - name: Check if failed
        run: if [[ $FAILED -eq 1 ]]; then exit 1; fi
