name: test
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: jfaz1/testing:latest
          run: |
            cd /github/workspace/
            ls -a >> $GITHUB_OUTPUT
