name: test
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: jfaz1/testing:latest
      volumes:
        - ${{ github.workspace }}:/work
      env:
        REPO_NAME: ${{ github.repository }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "Test"
        run: |
          cd /work/test && chmod +x ./test.sh && ./test.sh
          sleep 0.1 && lg -o && sleep 0.1
      - name: Save results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ github.workspace }}/test/results.csv
      - name: Check if failed
        run: |
          if [[ -f "/work/test/failed" ]]; then exit 1; fi
