name: test
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: jfaz1/testing:latest
          options: -v ${{ github.workspace }}:/work -e R=\033[0;31m -e Y=\033[1;33m -e G=\033[0;32m -e B=\033[0;34m
          run: |
            echo "\n${B}------- START TESTS -------"
            chmod +x /work/test/test.sh
            /work/test/test.sh            
            echo "${B}-------- END TESTS --------"
