jobs:
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: jfaz/testing:latest
          options: -v ${{ github.workspace }}:/
          run: |
            cd test
            ls >> $GITHUB_OUTPUT
