name: test
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: jfaz1/testing:latest
          options: -v ${{ github.workspace }}:/work -e B=\033[0;34m
          run: |
            echo "${B}------------------- START TESTS -------------------"
            cd /work/test
            chmod +x ./test.sh
            ./test.sh
            lg -o
            echo "${B}-------------------- END TESTS --------------------"
      - name: Save results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ github.workspace }}/test/results.csv